# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: edeltech
email: ""
description : We develop quality applications for desktop, embedded and mobile platforms.
facebook: https://www.facebook.com/edeltech/
logo: /assets/img/logo-edeltech.png

baseurl: "/edeltech" # the subpath of your site, e.g. /blog
url: "https://edeltech.github.io/edeltech" # the base hostname & protocol for your site, e.g. http://example.com
#twitter_username: jekyllrb
github_username:  dyt200

defaults:
- scope:
    path: ""
    type: "team-members"
  values:
    layout: "team-member"


#traduction configuration :

index:
  en:
  fr: fr

desc:
  en: We develop quality applications for desktop, embedded and mobile platforms.
  fr: Nous développons des applications de qualité pour les plates-formes de bureau, embarquées et mobiles.
about:
  en: About us
  fr: À Propos
projects:
  en: what we do
  fr: nos domaines d'expertise
team:
  en: Team
  fr: Team
desc1-title:
  en: Description title 1
  fr: Titre de la description 1
desc1-content:
  en: Content of the first description Content of the first description Content of the first description Content of the first description Content of the first description Content of the first description
  fr: Contenu de la première description Contenu de la première description Contenu de la première description Contenu de la première description Contenu de la première description Contenu de la première description
desc2-title:
  en: Description title 2
  fr: Titre de la description 2
desc2-content:
  en: Content of the second description Content of the second description Content of the second description Content of the second description Content of the second description Content of the second description
  fr: Contenu de la seconde description  Contenu de la seconde description  Contenu de la seconde description Contenu de la seconde description  Contenu de la seconde description  Contenu de la seconde description

project-title-1:
  en: Front-end
  fr: Front-end
project-title-2:
  en: Back-end
  fr: Back-end
project-title-3:
  en: Middle-ware
  fr: Middle-ware

project-desc-1:
  en: desc1 en
  fr: desc1 fr
project-desc-2:
  en: desc2 en
  fr: desc2 fr
project-desc-3:
  en: desc3 en
  fr: desc3 fr

posts-title:
  en: Posts
  fr: Articles

posts-title-home:
  en : Some of our blog posts
  fr : Quelques-uns de nos articles

view-post:
  en : +
  fr : +

arr:
  en: All Rights Reserved
  fr: Tous droits réservés

contact:
  en: Any questions ?
  fr: Des questions ?
contactText:
  en: Send us a message
  fr: Envoyez-nous un un message
contactSubject:
  en: Contact request via edeltech.ch
  fr: Demande de contact via edeltech.ch


collections:
  team-members:
      output: true


# Build settings
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag

# A list of the pages to display in the navigation bar
header_pages:

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
exclude:
  - Gemfile
  - Gemfile.lock
  - node_modules
  - update_boostrap.sh

