import {
  AcademicCapIcon as AcademicCapIconOutline,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalIconOutline,
  AdjustmentsVerticalIcon as AdjustmentsVerticalIconOutline,
  ArchiveBoxArrowDownIcon as ArchiveBoxArrowDownIconOutline,
  ArchiveBoxIcon as ArchiveBoxIconOutline,
  ArchiveBoxXMarkIcon as ArchiveBoxXMarkIconOutline,
  ArrowDownCircleIcon as ArrowDownCircleIconOutline,
  ArrowDownIcon as ArrowDownIconOutline,
  ArrowDownLeftIcon as ArrowDownLeftIconOutline,
  ArrowDownOnSquareIcon as ArrowDownOnSquareIconOutline,
  ArrowDownOnSquareStackIcon as ArrowDownOnSquareStackIconOutline,
  ArrowDownRightIcon as ArrowDownRightIconOutline,
  ArrowDownTrayIcon as ArrowDownTrayIconOutline,
  ArrowLeftCircleIcon as ArrowLeftCircleIconOutline,
  ArrowLeftIcon as ArrowLeftIconOutline,
  ArrowLeftOnRectangleIcon as ArrowLeftOnRectangleIconOutline,
  ArrowLongDownIcon as ArrowLongDownIconOutline,
  ArrowLongLeftIcon as ArrowLongLeftIconOutline,
  ArrowLongRightIcon as ArrowLongRightIconOutline,
  ArrowLongUpIcon as ArrowLongUpIconOutline,
  ArrowPathIcon as ArrowPathIconOutline,
  ArrowPathRoundedSquareIcon as ArrowPathRoundedSquareIconOutline,
  ArrowRightCircleIcon as ArrowRightCircleIconOutline,
  ArrowRightIcon as ArrowRightIconOutline,
  ArrowRightOnRectangleIcon as ArrowRightOnRectangleIconOutline,
  ArrowSmallDownIcon as ArrowSmallDownIconOutline,
  ArrowSmallLeftIcon as ArrowSmallLeftIconOutline,
  ArrowSmallRightIcon as ArrowSmallRightIconOutline,
  ArrowSmallUpIcon as ArrowSmallUpIconOutline,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareIconOutline,
  ArrowTrendingDownIcon as ArrowTrendingDownIconOutline,
  ArrowTrendingUpIcon as ArrowTrendingUpIconOutline,
  ArrowUpCircleIcon as ArrowUpCircleIconOutline,
  ArrowUpIcon as ArrowUpIconOutline,
  ArrowUpLeftIcon as ArrowUpLeftIconOutline,
  ArrowUpOnSquareIcon as ArrowUpOnSquareIconOutline,
  ArrowUpOnSquareStackIcon as ArrowUpOnSquareStackIconOutline,
  ArrowUpRightIcon as ArrowUpRightIconOutline,
  ArrowUpTrayIcon as ArrowUpTrayIconOutline,
  ArrowUturnDownIcon as ArrowUturnDownIconOutline,
  ArrowUturnLeftIcon as ArrowUturnLeftIconOutline,
  ArrowUturnRightIcon as ArrowUturnRightIconOutline,
  ArrowUturnUpIcon as ArrowUturnUpIconOutline,
  ArrowsPointingInIcon as ArrowsPointingInIconOutline,
  ArrowsPointingOutIcon as ArrowsPointingOutIconOutline,
  ArrowsRightLeftIcon as ArrowsRightLeftIconOutline,
  ArrowsUpDownIcon as ArrowsUpDownIconOutline,
  AtSymbolIcon as AtSymbolIconOutline,
  BackspaceIcon as BackspaceIconOutline,
  BackwardIcon as BackwardIconOutline,
  BanknotesIcon as BanknotesIconOutline,
  Bars2Icon as Bars2IconOutline,
  Bars3BottomLeftIcon as Bars3BottomLeftIconOutline,
  Bars3BottomRightIcon as Bars3BottomRightIconOutline,
  Bars3CenterLeftIcon as Bars3CenterLeftIconOutline,
  Bars3Icon as Bars3IconOutline,
  Bars4Icon as Bars4IconOutline,
  BarsArrowDownIcon as BarsArrowDownIconOutline,
  BarsArrowUpIcon as BarsArrowUpIconOutline,
  Battery0Icon as Battery0IconOutline,
  Battery100Icon as Battery100IconOutline,
  Battery50Icon as Battery50IconOutline,
  BeakerIcon as BeakerIconOutline,
  BellAlertIcon as BellAlertIconOutline,
  BellIcon as BellIconOutline,
  BellSlashIcon as BellSlashIconOutline,
  BellSnoozeIcon as BellSnoozeIconOutline,
  BoltIcon as BoltIconOutline,
  BoltSlashIcon as BoltSlashIconOutline,
  BookOpenIcon as BookOpenIconOutline,
  BookmarkIcon as BookmarkIconOutline,
  BookmarkSlashIcon as BookmarkSlashIconOutline,
  BookmarkSquareIcon as BookmarkSquareIconOutline,
  BriefcaseIcon as BriefcaseIconOutline,
  BugAntIcon as BugAntIconOutline,
  BuildingLibraryIcon as BuildingLibraryIconOutline,
  BuildingOffice2Icon as BuildingOffice2IconOutline,
  BuildingOfficeIcon as BuildingOfficeIconOutline,
  BuildingStorefrontIcon as BuildingStorefrontIconOutline,
  CakeIcon as CakeIconOutline,
  CalculatorIcon as CalculatorIconOutline,
  CalendarDaysIcon as CalendarDaysIconOutline,
  CalendarIcon as CalendarIconOutline,
  CameraIcon as CameraIconOutline,
  ChartBarIcon as ChartBarIconOutline,
  ChartBarSquareIcon as ChartBarSquareIconOutline,
  ChartPieIcon as ChartPieIconOutline,
  ChatBubbleBottomCenterIcon as ChatBubbleBottomCenterIconOutline,
  ChatBubbleBottomCenterTextIcon as ChatBubbleBottomCenterTextIconOutline,
  ChatBubbleLeftEllipsisIcon as ChatBubbleLeftEllipsisIconOutline,
  ChatBubbleLeftIcon as ChatBubbleLeftIconOutline,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightIconOutline,
  ChatBubbleOvalLeftEllipsisIcon as ChatBubbleOvalLeftEllipsisIconOutline,
  ChatBubbleOvalLeftIcon as ChatBubbleOvalLeftIconOutline,
  CheckBadgeIcon as CheckBadgeIconOutline,
  CheckCircleIcon as CheckCircleIconOutline,
  CheckIcon as CheckIconOutline,
  ChevronDoubleDownIcon as ChevronDoubleDownIconOutline,
  ChevronDoubleLeftIcon as ChevronDoubleLeftIconOutline,
  ChevronDoubleRightIcon as ChevronDoubleRightIconOutline,
  ChevronDoubleUpIcon as ChevronDoubleUpIconOutline,
  ChevronDownIcon as ChevronDownIconOutline,
  ChevronLeftIcon as ChevronLeftIconOutline,
  ChevronRightIcon as ChevronRightIconOutline,
  ChevronUpDownIcon as ChevronUpDownIconOutline,
  ChevronUpIcon as ChevronUpIconOutline,
  CircleStackIcon as CircleStackIconOutline,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheckIconOutline,
  ClipboardDocumentIcon as ClipboardDocumentIconOutline,
  ClipboardDocumentListIcon as ClipboardDocumentListIconOutline,
  ClipboardIcon as ClipboardIconOutline,
  ClockIcon as ClockIconOutline,
  CloudArrowDownIcon as CloudArrowDownIconOutline,
  CloudArrowUpIcon as CloudArrowUpIconOutline,
  CloudIcon as CloudIconOutline,
  CodeBracketIcon as CodeBracketIconOutline,
  CodeBracketSquareIcon as CodeBracketSquareIconOutline,
  Cog6ToothIcon as Cog6ToothIconOutline,
  Cog8ToothIcon as Cog8ToothIconOutline,
  CogIcon as CogIconOutline,
  CommandLineIcon as CommandLineIconOutline,
  ComputerDesktopIcon as ComputerDesktopIconOutline,
  CpuChipIcon as CpuChipIconOutline,
  CreditCardIcon as CreditCardIconOutline,
  CubeIcon as CubeIconOutline,
  CubeTransparentIcon as CubeTransparentIconOutline,
  CurrencyBangladeshiIcon as CurrencyBangladeshiIconOutline,
  CurrencyDollarIcon as CurrencyDollarIconOutline,
  CurrencyEuroIcon as CurrencyEuroIconOutline,
  CurrencyPoundIcon as CurrencyPoundIconOutline,
  CurrencyRupeeIcon as CurrencyRupeeIconOutline,
  CurrencyYenIcon as CurrencyYenIconOutline,
  CursorArrowRaysIcon as CursorArrowRaysIconOutline,
  CursorArrowRippleIcon as CursorArrowRippleIconOutline,
  DevicePhoneMobileIcon as DevicePhoneMobileIconOutline,
  DeviceTabletIcon as DeviceTabletIconOutline,
  DocumentArrowDownIcon as DocumentArrowDownIconOutline,
  DocumentArrowUpIcon as DocumentArrowUpIconOutline,
  DocumentChartBarIcon as DocumentChartBarIconOutline,
  DocumentCheckIcon as DocumentCheckIconOutline,
  DocumentDuplicateIcon as DocumentDuplicateIconOutline,
  DocumentIcon as DocumentIconOutline,
  DocumentMagnifyingGlassIcon as DocumentMagnifyingGlassIconOutline,
  DocumentMinusIcon as DocumentMinusIconOutline,
  DocumentPlusIcon as DocumentPlusIconOutline,
  DocumentTextIcon as DocumentTextIconOutline,
  EllipsisHorizontalCircleIcon as EllipsisHorizontalCircleIconOutline,
  EllipsisHorizontalIcon as EllipsisHorizontalIconOutline,
  EllipsisVerticalIcon as EllipsisVerticalIconOutline,
  EnvelopeIcon as EnvelopeIconOutline,
  EnvelopeOpenIcon as EnvelopeOpenIconOutline,
  ExclamationCircleIcon as ExclamationCircleIconOutline,
  ExclamationTriangleIcon as ExclamationTriangleIconOutline,
  EyeDropperIcon as EyeDropperIconOutline,
  EyeIcon as EyeIconOutline,
  EyeSlashIcon as EyeSlashIconOutline,
  FaceFrownIcon as FaceFrownIconOutline,
  FaceSmileIcon as FaceSmileIconOutline,
  FilmIcon as FilmIconOutline,
  FingerPrintIcon as FingerPrintIconOutline,
  FireIcon as FireIconOutline,
  FlagIcon as FlagIconOutline,
  FolderArrowDownIcon as FolderArrowDownIconOutline,
  FolderIcon as FolderIconOutline,
  FolderMinusIcon as FolderMinusIconOutline,
  FolderOpenIcon as FolderOpenIconOutline,
  FolderPlusIcon as FolderPlusIconOutline,
  ForwardIcon as ForwardIconOutline,
  FunnelIcon as FunnelIconOutline,
  GifIcon as GifIconOutline,
  GiftIcon as GiftIconOutline,
  GiftTopIcon as GiftTopIconOutline,
  GlobeAltIcon as GlobeAltIconOutline,
  GlobeAmericasIcon as GlobeAmericasIconOutline,
  GlobeAsiaAustraliaIcon as GlobeAsiaAustraliaIconOutline,
  GlobeEuropeAfricaIcon as GlobeEuropeAfricaIconOutline,
  HandRaisedIcon as HandRaisedIconOutline,
  HandThumbDownIcon as HandThumbDownIconOutline,
  HandThumbUpIcon as HandThumbUpIconOutline,
  HashtagIcon as HashtagIconOutline,
  HeartIcon as HeartIconOutline,
  HomeIcon as HomeIconOutline,
  HomeModernIcon as HomeModernIconOutline,
  IdentificationIcon as IdentificationIconOutline,
  InboxArrowDownIcon as InboxArrowDownIconOutline,
  InboxIcon as InboxIconOutline,
  InboxStackIcon as InboxStackIconOutline,
  InformationCircleIcon as InformationCircleIconOutline,
  KeyIcon as KeyIconOutline,
  LanguageIcon as LanguageIconOutline,
  LifebuoyIcon as LifebuoyIconOutline,
  LightBulbIcon as LightBulbIconOutline,
  LinkIcon as LinkIconOutline,
  ListBulletIcon as ListBulletIconOutline,
  LockClosedIcon as LockClosedIconOutline,
  LockOpenIcon as LockOpenIconOutline,
  MagnifyingGlassCircleIcon as MagnifyingGlassCircleIconOutline,
  MagnifyingGlassIcon as MagnifyingGlassIconOutline,
  MagnifyingGlassMinusIcon as MagnifyingGlassMinusIconOutline,
  MagnifyingGlassPlusIcon as MagnifyingGlassPlusIconOutline,
  MapIcon as MapIconOutline,
  MapPinIcon as MapPinIconOutline,
  MegaphoneIcon as MegaphoneIconOutline,
  MicrophoneIcon as MicrophoneIconOutline,
  MinusCircleIcon as MinusCircleIconOutline,
  MinusIcon as MinusIconOutline,
  MinusSmallIcon as MinusSmallIconOutline,
  MoonIcon as MoonIconOutline,
  MusicalNoteIcon as MusicalNoteIconOutline,
  NewspaperIcon as NewspaperIconOutline,
  NoSymbolIcon as NoSymbolIconOutline,
  PaintBrushIcon as PaintBrushIconOutline,
  PaperAirplaneIcon as PaperAirplaneIconOutline,
  PaperClipIcon as PaperClipIconOutline,
  PauseCircleIcon as PauseCircleIconOutline,
  PauseIcon as PauseIconOutline,
  PencilIcon as PencilIconOutline,
  PencilSquareIcon as PencilSquareIconOutline,
  PhoneArrowDownLeftIcon as PhoneArrowDownLeftIconOutline,
  PhoneArrowUpRightIcon as PhoneArrowUpRightIconOutline,
  PhoneIcon as PhoneIconOutline,
  PhoneXMarkIcon as PhoneXMarkIconOutline,
  PhotoIcon as PhotoIconOutline,
  PlayCircleIcon as PlayCircleIconOutline,
  PlayIcon as PlayIconOutline,
  PlayPauseIcon as PlayPauseIconOutline,
  PlusCircleIcon as PlusCircleIconOutline,
  PlusIcon as PlusIconOutline,
  PlusSmallIcon as PlusSmallIconOutline,
  PowerIcon as PowerIconOutline,
  PresentationChartBarIcon as PresentationChartBarIconOutline,
  PresentationChartLineIcon as PresentationChartLineIconOutline,
  PrinterIcon as PrinterIconOutline,
  PuzzlePieceIcon as PuzzlePieceIconOutline,
  QrCodeIcon as QrCodeIconOutline,
  QuestionMarkCircleIcon as QuestionMarkCircleIconOutline,
  QueueListIcon as QueueListIconOutline,
  RadioIcon as RadioIconOutline,
  ReceiptPercentIcon as ReceiptPercentIconOutline,
  ReceiptRefundIcon as ReceiptRefundIconOutline,
  RectangleGroupIcon as RectangleGroupIconOutline,
  RectangleStackIcon as RectangleStackIconOutline,
  RocketLaunchIcon as RocketLaunchIconOutline,
  RssIcon as RssIconOutline,
  ScaleIcon as ScaleIconOutline,
  ScissorsIcon as ScissorsIconOutline,
  ServerIcon as ServerIconOutline,
  ServerStackIcon as ServerStackIconOutline,
  ShareIcon as ShareIconOutline,
  ShieldCheckIcon as ShieldCheckIconOutline,
  ShieldExclamationIcon as ShieldExclamationIconOutline,
  ShoppingBagIcon as ShoppingBagIconOutline,
  ShoppingCartIcon as ShoppingCartIconOutline,
  SignalIcon as SignalIconOutline,
  SignalSlashIcon as SignalSlashIconOutline,
  SparklesIcon as SparklesIconOutline,
  SpeakerWaveIcon as SpeakerWaveIconOutline,
  SpeakerXMarkIcon as SpeakerXMarkIconOutline,
  Square2StackIcon as Square2StackIconOutline,
  Square3Stack3DIcon as Square3Stack3DIconOutline,
  Squares2X2Icon as Squares2X2IconOutline,
  SquaresPlusIcon as SquaresPlusIconOutline,
  StarIcon as StarIconOutline,
  StopCircleIcon as StopCircleIconOutline,
  StopIcon as StopIconOutline,
  SunIcon as SunIconOutline,
  SwatchIcon as SwatchIconOutline,
  TableCellsIcon as TableCellsIconOutline,
  TagIcon as TagIconOutline,
  TicketIcon as TicketIconOutline,
  TrashIcon as TrashIconOutline,
  TrophyIcon as TrophyIconOutline,
  TruckIcon as TruckIconOutline,
  TvIcon as TvIconOutline,
  UserCircleIcon as UserCircleIconOutline,
  UserGroupIcon as UserGroupIconOutline,
  UserIcon as UserIconOutline,
  UserMinusIcon as UserMinusIconOutline,
  UserPlusIcon as UserPlusIconOutline,
  UsersIcon as UsersIconOutline,
  VariableIcon as VariableIconOutline,
  VideoCameraIcon as VideoCameraIconOutline,
  VideoCameraSlashIcon as VideoCameraSlashIconOutline,
  ViewColumnsIcon as ViewColumnsIconOutline,
  ViewfinderCircleIcon as ViewfinderCircleIconOutline,
  WalletIcon as WalletIconOutline,
  WifiIcon as WifiIconOutline,
  WindowIcon as WindowIconOutline,
  WrenchIcon as WrenchIconOutline,
  WrenchScrewdriverIcon as WrenchScrewdriverIconOutline,
  XCircleIcon as XCircleIconOutline,
  XMarkIcon as XMarkIconOutline
} from '@heroicons/react/24/outline'
import {
  AcademicCapIcon as AcademicCapIconSolid,
  AdjustmentsHorizontalIcon as AdjustmentsHorizontalIconSolid,
  AdjustmentsVerticalIcon as AdjustmentsVerticalIconSolid,
  ArchiveBoxArrowDownIcon as ArchiveBoxArrowDownIconSolid,
  ArchiveBoxIcon as ArchiveBoxIconSolid,
  ArchiveBoxXMarkIcon as ArchiveBoxXMarkIconSolid,
  ArrowDownCircleIcon as ArrowDownCircleIconSolid,
  ArrowDownIcon as ArrowDownIconSolid,
  ArrowDownLeftIcon as ArrowDownLeftIconSolid,
  ArrowDownOnSquareIcon as ArrowDownOnSquareIconSolid,
  ArrowDownOnSquareStackIcon as ArrowDownOnSquareStackIconSolid,
  ArrowDownRightIcon as ArrowDownRightIconSolid,
  ArrowDownTrayIcon as ArrowDownTrayIconSolid,
  ArrowLeftCircleIcon as ArrowLeftCircleIconSolid,
  ArrowLeftIcon as ArrowLeftIconSolid,
  ArrowLeftOnRectangleIcon as ArrowLeftOnRectangleIconSolid,
  ArrowLongDownIcon as ArrowLongDownIconSolid,
  ArrowLongLeftIcon as ArrowLongLeftIconSolid,
  ArrowLongRightIcon as ArrowLongRightIconSolid,
  ArrowLongUpIcon as ArrowLongUpIconSolid,
  ArrowPathIcon as ArrowPathIconSolid,
  ArrowPathRoundedSquareIcon as ArrowPathRoundedSquareIconSolid,
  ArrowRightCircleIcon as ArrowRightCircleIconSolid,
  ArrowRightIcon as ArrowRightIconSolid,
  ArrowRightOnRectangleIcon as ArrowRightOnRectangleIconSolid,
  ArrowSmallDownIcon as ArrowSmallDownIconSolid,
  ArrowSmallLeftIcon as ArrowSmallLeftIconSolid,
  ArrowSmallRightIcon as ArrowSmallRightIconSolid,
  ArrowSmallUpIcon as ArrowSmallUpIconSolid,
  ArrowTopRightOnSquareIcon as ArrowTopRightOnSquareIconSolid,
  ArrowTrendingDownIcon as ArrowTrendingDownIconSolid,
  ArrowTrendingUpIcon as ArrowTrendingUpIconSolid,
  ArrowUpCircleIcon as ArrowUpCircleIconSolid,
  ArrowUpIcon as ArrowUpIconSolid,
  ArrowUpLeftIcon as ArrowUpLeftIconSolid,
  ArrowUpOnSquareIcon as ArrowUpOnSquareIconSolid,
  ArrowUpOnSquareStackIcon as ArrowUpOnSquareStackIconSolid,
  ArrowUpRightIcon as ArrowUpRightIconSolid,
  ArrowUpTrayIcon as ArrowUpTrayIconSolid,
  ArrowUturnDownIcon as ArrowUturnDownIconSolid,
  ArrowUturnLeftIcon as ArrowUturnLeftIconSolid,
  ArrowUturnRightIcon as ArrowUturnRightIconSolid,
  ArrowUturnUpIcon as ArrowUturnUpIconSolid,
  ArrowsPointingInIcon as ArrowsPointingInIconSolid,
  ArrowsPointingOutIcon as ArrowsPointingOutIconSolid,
  ArrowsRightLeftIcon as ArrowsRightLeftIconSolid,
  ArrowsUpDownIcon as ArrowsUpDownIconSolid,
  AtSymbolIcon as AtSymbolIconSolid,
  BackspaceIcon as BackspaceIconSolid,
  BackwardIcon as BackwardIconSolid,
  BanknotesIcon as BanknotesIconSolid,
  Bars2Icon as Bars2IconSolid,
  Bars3BottomLeftIcon as Bars3BottomLeftIconSolid,
  Bars3BottomRightIcon as Bars3BottomRightIconSolid,
  Bars3CenterLeftIcon as Bars3CenterLeftIconSolid,
  Bars3Icon as Bars3IconSolid,
  Bars4Icon as Bars4IconSolid,
  BarsArrowDownIcon as BarsArrowDownIconSolid,
  BarsArrowUpIcon as BarsArrowUpIconSolid,
  Battery0Icon as Battery0IconSolid,
  Battery100Icon as Battery100IconSolid,
  Battery50Icon as Battery50IconSolid,
  BeakerIcon as BeakerIconSolid,
  BellAlertIcon as BellAlertIconSolid,
  BellIcon as BellIconSolid,
  BellSlashIcon as BellSlashIconSolid,
  BellSnoozeIcon as BellSnoozeIconSolid,
  BoltIcon as BoltIconSolid,
  BoltSlashIcon as BoltSlashIconSolid,
  BookOpenIcon as BookOpenIconSolid,
  BookmarkIcon as BookmarkIconSolid,
  BookmarkSlashIcon as BookmarkSlashIconSolid,
  BookmarkSquareIcon as BookmarkSquareIconSolid,
  BriefcaseIcon as BriefcaseIconSolid,
  BugAntIcon as BugAntIconSolid,
  BuildingLibraryIcon as BuildingLibraryIconSolid,
  BuildingOffice2Icon as BuildingOffice2IconSolid,
  BuildingOfficeIcon as BuildingOfficeIconSolid,
  BuildingStorefrontIcon as BuildingStorefrontIconSolid,
  CakeIcon as CakeIconSolid,
  CalculatorIcon as CalculatorIconSolid,
  CalendarDaysIcon as CalendarDaysIconSolid,
  CalendarIcon as CalendarIconSolid,
  CameraIcon as CameraIconSolid,
  ChartBarIcon as ChartBarIconSolid,
  ChartBarSquareIcon as ChartBarSquareIconSolid,
  ChartPieIcon as ChartPieIconSolid,
  ChatBubbleBottomCenterIcon as ChatBubbleBottomCenterIconSolid,
  ChatBubbleBottomCenterTextIcon as ChatBubbleBottomCenterTextIconSolid,
  ChatBubbleLeftEllipsisIcon as ChatBubbleLeftEllipsisIconSolid,
  ChatBubbleLeftIcon as ChatBubbleLeftIconSolid,
  ChatBubbleLeftRightIcon as ChatBubbleLeftRightIconSolid,
  ChatBubbleOvalLeftEllipsisIcon as ChatBubbleOvalLeftEllipsisIconSolid,
  ChatBubbleOvalLeftIcon as ChatBubbleOvalLeftIconSolid,
  CheckBadgeIcon as CheckBadgeIconSolid,
  CheckCircleIcon as CheckCircleIconSolid,
  CheckIcon as CheckIconSolid,
  ChevronDoubleDownIcon as ChevronDoubleDownIconSolid,
  ChevronDoubleLeftIcon as ChevronDoubleLeftIconSolid,
  ChevronDoubleRightIcon as ChevronDoubleRightIconSolid,
  ChevronDoubleUpIcon as ChevronDoubleUpIconSolid,
  ChevronDownIcon as ChevronDownIconSolid,
  ChevronLeftIcon as ChevronLeftIconSolid,
  ChevronRightIcon as ChevronRightIconSolid,
  ChevronUpDownIcon as ChevronUpDownIconSolid,
  ChevronUpIcon as ChevronUpIconSolid,
  CircleStackIcon as CircleStackIconSolid,
  ClipboardDocumentCheckIcon as ClipboardDocumentCheckIconSolid,
  ClipboardDocumentIcon as ClipboardDocumentIconSolid,
  ClipboardDocumentListIcon as ClipboardDocumentListIconSolid,
  ClipboardIcon as ClipboardIconSolid,
  ClockIcon as ClockIconSolid,
  CloudArrowDownIcon as CloudArrowDownIconSolid,
  CloudArrowUpIcon as CloudArrowUpIconSolid,
  CloudIcon as CloudIconSolid,
  CodeBracketIcon as CodeBracketIconSolid,
  CodeBracketSquareIcon as CodeBracketSquareIconSolid,
  Cog6ToothIcon as Cog6ToothIconSolid,
  Cog8ToothIcon as Cog8ToothIconSolid,
  CogIcon as CogIconSolid,
  CommandLineIcon as CommandLineIconSolid,
  ComputerDesktopIcon as ComputerDesktopIconSolid,
  CpuChipIcon as CpuChipIconSolid,
  CreditCardIcon as CreditCardIconSolid,
  CubeIcon as CubeIconSolid,
  CubeTransparentIcon as CubeTransparentIconSolid,
  CurrencyBangladeshiIcon as CurrencyBangladeshiIconSolid,
  CurrencyDollarIcon as CurrencyDollarIconSolid,
  CurrencyEuroIcon as CurrencyEuroIconSolid,
  CurrencyPoundIcon as CurrencyPoundIconSolid,
  CurrencyRupeeIcon as CurrencyRupeeIconSolid,
  CurrencyYenIcon as CurrencyYenIconSolid,
  CursorArrowRaysIcon as CursorArrowRaysIconSolid,
  CursorArrowRippleIcon as CursorArrowRippleIconSolid,
  DevicePhoneMobileIcon as DevicePhoneMobileIconSolid,
  DeviceTabletIcon as DeviceTabletIconSolid,
  DocumentArrowDownIcon as DocumentArrowDownIconSolid,
  DocumentArrowUpIcon as DocumentArrowUpIconSolid,
  DocumentChartBarIcon as DocumentChartBarIconSolid,
  DocumentCheckIcon as DocumentCheckIconSolid,
  DocumentDuplicateIcon as DocumentDuplicateIconSolid,
  DocumentIcon as DocumentIconSolid,
  DocumentMagnifyingGlassIcon as DocumentMagnifyingGlassIconSolid,
  DocumentMinusIcon as DocumentMinusIconSolid,
  DocumentPlusIcon as DocumentPlusIconSolid,
  DocumentTextIcon as DocumentTextIconSolid,
  EllipsisHorizontalCircleIcon as EllipsisHorizontalCircleIconSolid,
  EllipsisHorizontalIcon as EllipsisHorizontalIconSolid,
  EllipsisVerticalIcon as EllipsisVerticalIconSolid,
  EnvelopeIcon as EnvelopeIconSolid,
  EnvelopeOpenIcon as EnvelopeOpenIconSolid,
  ExclamationCircleIcon as ExclamationCircleIconSolid,
  ExclamationTriangleIcon as ExclamationTriangleIconSolid,
  EyeDropperIcon as EyeDropperIconSolid,
  EyeIcon as EyeIconSolid,
  EyeSlashIcon as EyeSlashIconSolid,
  FaceFrownIcon as FaceFrownIconSolid,
  FaceSmileIcon as FaceSmileIconSolid,
  FilmIcon as FilmIconSolid,
  FingerPrintIcon as FingerPrintIconSolid,
  FireIcon as FireIconSolid,
  FlagIcon as FlagIconSolid,
  FolderArrowDownIcon as FolderArrowDownIconSolid,
  FolderIcon as FolderIconSolid,
  FolderMinusIcon as FolderMinusIconSolid,
  FolderOpenIcon as FolderOpenIconSolid,
  FolderPlusIcon as FolderPlusIconSolid,
  ForwardIcon as ForwardIconSolid,
  FunnelIcon as FunnelIconSolid,
  GifIcon as GifIconSolid,
  GiftIcon as GiftIconSolid,
  GiftTopIcon as GiftTopIconSolid,
  GlobeAltIcon as GlobeAltIconSolid,
  GlobeAmericasIcon as GlobeAmericasIconSolid,
  GlobeAsiaAustraliaIcon as GlobeAsiaAustraliaIconSolid,
  GlobeEuropeAfricaIcon as GlobeEuropeAfricaIconSolid,
  HandRaisedIcon as HandRaisedIconSolid,
  HandThumbDownIcon as HandThumbDownIconSolid,
  HandThumbUpIcon as HandThumbUpIconSolid,
  HashtagIcon as HashtagIconSolid,
  HeartIcon as HeartIconSolid,
  HomeIcon as HomeIconSolid,
  HomeModernIcon as HomeModernIconSolid,
  IdentificationIcon as IdentificationIconSolid,
  InboxArrowDownIcon as InboxArrowDownIconSolid,
  InboxIcon as InboxIconSolid,
  InboxStackIcon as InboxStackIconSolid,
  InformationCircleIcon as InformationCircleIconSolid,
  KeyIcon as KeyIconSolid,
  LanguageIcon as LanguageIconSolid,
  LifebuoyIcon as LifebuoyIconSolid,
  LightBulbIcon as LightBulbIconSolid,
  LinkIcon as LinkIconSolid,
  ListBulletIcon as ListBulletIconSolid,
  LockClosedIcon as LockClosedIconSolid,
  LockOpenIcon as LockOpenIconSolid,
  MagnifyingGlassCircleIcon as MagnifyingGlassCircleIconSolid,
  MagnifyingGlassIcon as MagnifyingGlassIconSolid,
  MagnifyingGlassMinusIcon as MagnifyingGlassMinusIconSolid,
  MagnifyingGlassPlusIcon as MagnifyingGlassPlusIconSolid,
  MapIcon as MapIconSolid,
  MapPinIcon as MapPinIconSolid,
  MegaphoneIcon as MegaphoneIconSolid,
  MicrophoneIcon as MicrophoneIconSolid,
  MinusCircleIcon as MinusCircleIconSolid,
  MinusIcon as MinusIconSolid,
  MinusSmallIcon as MinusSmallIconSolid,
  MoonIcon as MoonIconSolid,
  MusicalNoteIcon as MusicalNoteIconSolid,
  NewspaperIcon as NewspaperIconSolid,
  NoSymbolIcon as NoSymbolIconSolid,
  PaintBrushIcon as PaintBrushIconSolid,
  PaperAirplaneIcon as PaperAirplaneIconSolid,
  PaperClipIcon as PaperClipIconSolid,
  PauseCircleIcon as PauseCircleIconSolid,
  PauseIcon as PauseIconSolid,
  PencilIcon as PencilIconSolid,
  PencilSquareIcon as PencilSquareIconSolid,
  PhoneArrowDownLeftIcon as PhoneArrowDownLeftIconSolid,
  PhoneArrowUpRightIcon as PhoneArrowUpRightIconSolid,
  PhoneIcon as PhoneIconSolid,
  PhoneXMarkIcon as PhoneXMarkIconSolid,
  PhotoIcon as PhotoIconSolid,
  PlayCircleIcon as PlayCircleIconSolid,
  PlayIcon as PlayIconSolid,
  PlayPauseIcon as PlayPauseIconSolid,
  PlusCircleIcon as PlusCircleIconSolid,
  PlusIcon as PlusIconSolid,
  PlusSmallIcon as PlusSmallIconSolid,
  PowerIcon as PowerIconSolid,
  PresentationChartBarIcon as PresentationChartBarIconSolid,
  PresentationChartLineIcon as PresentationChartLineIconSolid,
  PrinterIcon as PrinterIconSolid,
  PuzzlePieceIcon as PuzzlePieceIconSolid,
  QrCodeIcon as QrCodeIconSolid,
  QuestionMarkCircleIcon as QuestionMarkCircleIconSolid,
  QueueListIcon as QueueListIconSolid,
  RadioIcon as RadioIconSolid,
  ReceiptPercentIcon as ReceiptPercentIconSolid,
  ReceiptRefundIcon as ReceiptRefundIconSolid,
  RectangleGroupIcon as RectangleGroupIconSolid,
  RectangleStackIcon as RectangleStackIconSolid,
  RocketLaunchIcon as RocketLaunchIconSolid,
  RssIcon as RssIconSolid,
  ScaleIcon as ScaleIconSolid,
  ScissorsIcon as ScissorsIconSolid,
  ServerIcon as ServerIconSolid,
  ServerStackIcon as ServerStackIconSolid,
  ShareIcon as ShareIconSolid,
  ShieldCheckIcon as ShieldCheckIconSolid,
  ShieldExclamationIcon as ShieldExclamationIconSolid,
  ShoppingBagIcon as ShoppingBagIconSolid,
  ShoppingCartIcon as ShoppingCartIconSolid,
  SignalIcon as SignalIconSolid,
  SignalSlashIcon as SignalSlashIconSolid,
  SparklesIcon as SparklesIconSolid,
  SpeakerWaveIcon as SpeakerWaveIconSolid,
  SpeakerXMarkIcon as SpeakerXMarkIconSolid,
  Square2StackIcon as Square2StackIconSolid,
  Square3Stack3DIcon as Square3Stack3DIconSolid,
  Squares2X2Icon as Squares2X2IconSolid,
  SquaresPlusIcon as SquaresPlusIconSolid,
  StarIcon as StarIconSolid,
  StopCircleIcon as StopCircleIconSolid,
  StopIcon as StopIconSolid,
  SunIcon as SunIconSolid,
  SwatchIcon as SwatchIconSolid,
  TableCellsIcon as TableCellsIconSolid,
  TagIcon as TagIconSolid,
  TicketIcon as TicketIconSolid,
  TrashIcon as TrashIconSolid,
  TrophyIcon as TrophyIconSolid,
  TruckIcon as TruckIconSolid,
  TvIcon as TvIconSolid,
  UserCircleIcon as UserCircleIconSolid,
  UserGroupIcon as UserGroupIconSolid,
  UserIcon as UserIconSolid,
  UserMinusIcon as UserMinusIconSolid,
  UserPlusIcon as UserPlusIconSolid,
  UsersIcon as UsersIconSolid,
  VariableIcon as VariableIconSolid,
  VideoCameraIcon as VideoCameraIconSolid,
  VideoCameraSlashIcon as VideoCameraSlashIconSolid,
  ViewColumnsIcon as ViewColumnsIconSolid,
  ViewfinderCircleIcon as ViewfinderCircleIconSolid,
  WalletIcon as WalletIconSolid,
  WifiIcon as WifiIconSolid,
  WindowIcon as WindowIconSolid,
  WrenchIcon as WrenchIconSolid,
  WrenchScrewdriverIcon as WrenchScrewdriverIconSolid,
  XCircleIcon as XCircleIconSolid,
  XMarkIcon as XMarkIconSolid
} from '@heroicons/react/24/solid'
import {IconType} from '@/models/icon.model'

export type IconProps = IconType & React.ComponentPropsWithoutRef<'svg'>

const icons = {
  AcademicCapIconOutline,
  AdjustmentsHorizontalIconOutline,
  AdjustmentsVerticalIconOutline,
  ArchiveBoxArrowDownIconOutline,
  ArchiveBoxIconOutline,
  ArchiveBoxXMarkIconOutline,
  ArrowDownCircleIconOutline,
  ArrowDownIconOutline,
  ArrowDownLeftIconOutline,
  ArrowDownOnSquareIconOutline,
  ArrowDownOnSquareStackIconOutline,
  ArrowDownRightIconOutline,
  ArrowDownTrayIconOutline,
  ArrowLeftCircleIconOutline,
  ArrowLeftIconOutline,
  ArrowLeftOnRectangleIconOutline,
  ArrowLongDownIconOutline,
  ArrowLongLeftIconOutline,
  ArrowLongRightIconOutline,
  ArrowLongUpIconOutline,
  ArrowPathIconOutline,
  ArrowPathRoundedSquareIconOutline,
  ArrowRightCircleIconOutline,
  ArrowRightIconOutline,
  ArrowRightOnRectangleIconOutline,
  ArrowSmallDownIconOutline,
  ArrowSmallLeftIconOutline,
  ArrowSmallRightIconOutline,
  ArrowSmallUpIconOutline,
  ArrowTopRightOnSquareIconOutline,
  ArrowTrendingDownIconOutline,
  ArrowTrendingUpIconOutline,
  ArrowUpCircleIconOutline,
  ArrowUpIconOutline,
  ArrowUpLeftIconOutline,
  ArrowUpOnSquareIconOutline,
  ArrowUpOnSquareStackIconOutline,
  ArrowUpRightIconOutline,
  ArrowUpTrayIconOutline,
  ArrowUturnDownIconOutline,
  ArrowUturnLeftIconOutline,
  ArrowUturnRightIconOutline,
  ArrowUturnUpIconOutline,
  ArrowsPointingInIconOutline,
  ArrowsPointingOutIconOutline,
  ArrowsRightLeftIconOutline,
  ArrowsUpDownIconOutline,
  AtSymbolIconOutline,
  BackspaceIconOutline,
  BackwardIconOutline,
  BanknotesIconOutline,
  Bars2IconOutline,
  Bars3BottomLeftIconOutline,
  Bars3BottomRightIconOutline,
  Bars3CenterLeftIconOutline,
  Bars3IconOutline,
  Bars4IconOutline,
  BarsArrowDownIconOutline,
  BarsArrowUpIconOutline,
  Battery0IconOutline,
  Battery100IconOutline,
  Battery50IconOutline,
  BeakerIconOutline,
  BellAlertIconOutline,
  BellIconOutline,
  BellSlashIconOutline,
  BellSnoozeIconOutline,
  BoltIconOutline,
  BoltSlashIconOutline,
  BookOpenIconOutline,
  BookmarkIconOutline,
  BookmarkSlashIconOutline,
  BookmarkSquareIconOutline,
  BriefcaseIconOutline,
  BugAntIconOutline,
  BuildingLibraryIconOutline,
  BuildingOffice2IconOutline,
  BuildingOfficeIconOutline,
  BuildingStorefrontIconOutline,
  CakeIconOutline,
  CalculatorIconOutline,
  CalendarDaysIconOutline,
  CalendarIconOutline,
  CameraIconOutline,
  ChartBarIconOutline,
  ChartBarSquareIconOutline,
  ChartPieIconOutline,
  ChatBubbleBottomCenterIconOutline,
  ChatBubbleBottomCenterTextIconOutline,
  ChatBubbleLeftEllipsisIconOutline,
  ChatBubbleLeftIconOutline,
  ChatBubbleLeftRightIconOutline,
  ChatBubbleOvalLeftEllipsisIconOutline,
  ChatBubbleOvalLeftIconOutline,
  CheckBadgeIconOutline,
  CheckCircleIconOutline,
  CheckIconOutline,
  ChevronDoubleDownIconOutline,
  ChevronDoubleLeftIconOutline,
  ChevronDoubleRightIconOutline,
  ChevronDoubleUpIconOutline,
  ChevronDownIconOutline,
  ChevronLeftIconOutline,
  ChevronRightIconOutline,
  ChevronUpDownIconOutline,
  ChevronUpIconOutline,
  CircleStackIconOutline,
  ClipboardDocumentCheckIconOutline,
  ClipboardDocumentIconOutline,
  ClipboardDocumentListIconOutline,
  ClipboardIconOutline,
  ClockIconOutline,
  CloudArrowDownIconOutline,
  CloudArrowUpIconOutline,
  CloudIconOutline,
  CodeBracketIconOutline,
  CodeBracketSquareIconOutline,
  Cog6ToothIconOutline,
  Cog8ToothIconOutline,
  CogIconOutline,
  CommandLineIconOutline,
  ComputerDesktopIconOutline,
  CpuChipIconOutline,
  CreditCardIconOutline,
  CubeIconOutline,
  CubeTransparentIconOutline,
  CurrencyBangladeshiIconOutline,
  CurrencyDollarIconOutline,
  CurrencyEuroIconOutline,
  CurrencyPoundIconOutline,
  CurrencyRupeeIconOutline,
  CurrencyYenIconOutline,
  CursorArrowRaysIconOutline,
  CursorArrowRippleIconOutline,
  DevicePhoneMobileIconOutline,
  DeviceTabletIconOutline,
  DocumentArrowDownIconOutline,
  DocumentArrowUpIconOutline,
  DocumentChartBarIconOutline,
  DocumentCheckIconOutline,
  DocumentDuplicateIconOutline,
  DocumentIconOutline,
  DocumentMagnifyingGlassIconOutline,
  DocumentMinusIconOutline,
  DocumentPlusIconOutline,
  DocumentTextIconOutline,
  EllipsisHorizontalCircleIconOutline,
  EllipsisHorizontalIconOutline,
  EllipsisVerticalIconOutline,
  EnvelopeIconOutline,
  EnvelopeOpenIconOutline,
  ExclamationCircleIconOutline,
  ExclamationTriangleIconOutline,
  EyeDropperIconOutline,
  EyeIconOutline,
  EyeSlashIconOutline,
  FaceFrownIconOutline,
  FaceSmileIconOutline,
  FilmIconOutline,
  FingerPrintIconOutline,
  FireIconOutline,
  FlagIconOutline,
  FolderArrowDownIconOutline,
  FolderIconOutline,
  FolderMinusIconOutline,
  FolderOpenIconOutline,
  FolderPlusIconOutline,
  ForwardIconOutline,
  FunnelIconOutline,
  GifIconOutline,
  GiftIconOutline,
  GiftTopIconOutline,
  GlobeAltIconOutline,
  GlobeAmericasIconOutline,
  GlobeAsiaAustraliaIconOutline,
  GlobeEuropeAfricaIconOutline,
  HandRaisedIconOutline,
  HandThumbDownIconOutline,
  HandThumbUpIconOutline,
  HashtagIconOutline,
  HeartIconOutline,
  HomeIconOutline,
  HomeModernIconOutline,
  IdentificationIconOutline,
  InboxArrowDownIconOutline,
  InboxIconOutline,
  InboxStackIconOutline,
  InformationCircleIconOutline,
  KeyIconOutline,
  LanguageIconOutline,
  LifebuoyIconOutline,
  LightBulbIconOutline,
  LinkIconOutline,
  ListBulletIconOutline,
  LockClosedIconOutline,
  LockOpenIconOutline,
  MagnifyingGlassCircleIconOutline,
  MagnifyingGlassIconOutline,
  MagnifyingGlassMinusIconOutline,
  MagnifyingGlassPlusIconOutline,
  MapIconOutline,
  MapPinIconOutline,
  MegaphoneIconOutline,
  MicrophoneIconOutline,
  MinusCircleIconOutline,
  MinusIconOutline,
  MinusSmallIconOutline,
  MoonIconOutline,
  MusicalNoteIconOutline,
  NewspaperIconOutline,
  NoSymbolIconOutline,
  PaintBrushIconOutline,
  PaperAirplaneIconOutline,
  PaperClipIconOutline,
  PauseCircleIconOutline,
  PauseIconOutline,
  PencilIconOutline,
  PencilSquareIconOutline,
  PhoneArrowDownLeftIconOutline,
  PhoneArrowUpRightIconOutline,
  PhoneIconOutline,
  PhoneXMarkIconOutline,
  PhotoIconOutline,
  PlayCircleIconOutline,
  PlayIconOutline,
  PlayPauseIconOutline,
  PlusCircleIconOutline,
  PlusIconOutline,
  PlusSmallIconOutline,
  PowerIconOutline,
  PresentationChartBarIconOutline,
  PresentationChartLineIconOutline,
  PrinterIconOutline,
  PuzzlePieceIconOutline,
  QrCodeIconOutline,
  QuestionMarkCircleIconOutline,
  QueueListIconOutline,
  RadioIconOutline,
  ReceiptPercentIconOutline,
  ReceiptRefundIconOutline,
  RectangleGroupIconOutline,
  RectangleStackIconOutline,
  RocketLaunchIconOutline,
  RssIconOutline,
  ScaleIconOutline,
  ScissorsIconOutline,
  ServerIconOutline,
  ServerStackIconOutline,
  ShareIconOutline,
  ShieldCheckIconOutline,
  ShieldExclamationIconOutline,
  ShoppingBagIconOutline,
  ShoppingCartIconOutline,
  SignalIconOutline,
  SignalSlashIconOutline,
  SparklesIconOutline,
  SpeakerWaveIconOutline,
  SpeakerXMarkIconOutline,
  Square2StackIconOutline,
  Square3Stack3DIconOutline,
  Squares2X2IconOutline,
  SquaresPlusIconOutline,
  StarIconOutline,
  StopCircleIconOutline,
  StopIconOutline,
  SunIconOutline,
  SwatchIconOutline,
  TableCellsIconOutline,
  TagIconOutline,
  TicketIconOutline,
  TrashIconOutline,
  TrophyIconOutline,
  TruckIconOutline,
  TvIconOutline,
  UserCircleIconOutline,
  UserGroupIconOutline,
  UserIconOutline,
  UserMinusIconOutline,
  UserPlusIconOutline,
  UsersIconOutline,
  VariableIconOutline,
  VideoCameraIconOutline,
  VideoCameraSlashIconOutline,
  ViewColumnsIconOutline,
  ViewfinderCircleIconOutline,
  WalletIconOutline,
  WifiIconOutline,
  WindowIconOutline,
  WrenchIconOutline,
  WrenchScrewdriverIconOutline,
  XCircleIconOutline,
  XMarkIconOutline,
  AcademicCapIconSolid,
  AdjustmentsHorizontalIconSolid,
  AdjustmentsVerticalIconSolid,
  ArchiveBoxArrowDownIconSolid,
  ArchiveBoxIconSolid,
  ArchiveBoxXMarkIconSolid,
  ArrowDownCircleIconSolid,
  ArrowDownIconSolid,
  ArrowDownLeftIconSolid,
  ArrowDownOnSquareIconSolid,
  ArrowDownOnSquareStackIconSolid,
  ArrowDownRightIconSolid,
  ArrowDownTrayIconSolid,
  ArrowLeftCircleIconSolid,
  ArrowLeftIconSolid,
  ArrowLeftOnRectangleIconSolid,
  ArrowLongDownIconSolid,
  ArrowLongLeftIconSolid,
  ArrowLongRightIconSolid,
  ArrowLongUpIconSolid,
  ArrowPathIconSolid,
  ArrowPathRoundedSquareIconSolid,
  ArrowRightCircleIconSolid,
  ArrowRightIconSolid,
  ArrowRightOnRectangleIconSolid,
  ArrowSmallDownIconSolid,
  ArrowSmallLeftIconSolid,
  ArrowSmallRightIconSolid,
  ArrowSmallUpIconSolid,
  ArrowTopRightOnSquareIconSolid,
  ArrowTrendingDownIconSolid,
  ArrowTrendingUpIconSolid,
  ArrowUpCircleIconSolid,
  ArrowUpIconSolid,
  ArrowUpLeftIconSolid,
  ArrowUpOnSquareIconSolid,
  ArrowUpOnSquareStackIconSolid,
  ArrowUpRightIconSolid,
  ArrowUpTrayIconSolid,
  ArrowUturnDownIconSolid,
  ArrowUturnLeftIconSolid,
  ArrowUturnRightIconSolid,
  ArrowUturnUpIconSolid,
  ArrowsPointingInIconSolid,
  ArrowsPointingOutIconSolid,
  ArrowsRightLeftIconSolid,
  ArrowsUpDownIconSolid,
  AtSymbolIconSolid,
  BackspaceIconSolid,
  BackwardIconSolid,
  BanknotesIconSolid,
  Bars2IconSolid,
  Bars3BottomLeftIconSolid,
  Bars3BottomRightIconSolid,
  Bars3CenterLeftIconSolid,
  Bars3IconSolid,
  Bars4IconSolid,
  BarsArrowDownIconSolid,
  BarsArrowUpIconSolid,
  Battery0IconSolid,
  Battery100IconSolid,
  Battery50IconSolid,
  BeakerIconSolid,
  BellAlertIconSolid,
  BellIconSolid,
  BellSlashIconSolid,
  BellSnoozeIconSolid,
  BoltIconSolid,
  BoltSlashIconSolid,
  BookOpenIconSolid,
  BookmarkIconSolid,
  BookmarkSlashIconSolid,
  BookmarkSquareIconSolid,
  BriefcaseIconSolid,
  BugAntIconSolid,
  BuildingLibraryIconSolid,
  BuildingOffice2IconSolid,
  BuildingOfficeIconSolid,
  BuildingStorefrontIconSolid,
  CakeIconSolid,
  CalculatorIconSolid,
  CalendarDaysIconSolid,
  CalendarIconSolid,
  CameraIconSolid,
  ChartBarIconSolid,
  ChartBarSquareIconSolid,
  ChartPieIconSolid,
  ChatBubbleBottomCenterIconSolid,
  ChatBubbleBottomCenterTextIconSolid,
  ChatBubbleLeftEllipsisIconSolid,
  ChatBubbleLeftIconSolid,
  ChatBubbleLeftRightIconSolid,
  ChatBubbleOvalLeftEllipsisIconSolid,
  ChatBubbleOvalLeftIconSolid,
  CheckBadgeIconSolid,
  CheckCircleIconSolid,
  CheckIconSolid,
  ChevronDoubleDownIconSolid,
  ChevronDoubleLeftIconSolid,
  ChevronDoubleRightIconSolid,
  ChevronDoubleUpIconSolid,
  ChevronDownIconSolid,
  ChevronLeftIconSolid,
  ChevronRightIconSolid,
  ChevronUpDownIconSolid,
  ChevronUpIconSolid,
  CircleStackIconSolid,
  ClipboardDocumentCheckIconSolid,
  ClipboardDocumentIconSolid,
  ClipboardDocumentListIconSolid,
  ClipboardIconSolid,
  ClockIconSolid,
  CloudArrowDownIconSolid,
  CloudArrowUpIconSolid,
  CloudIconSolid,
  CodeBracketIconSolid,
  CodeBracketSquareIconSolid,
  Cog6ToothIconSolid,
  Cog8ToothIconSolid,
  CogIconSolid,
  CommandLineIconSolid,
  ComputerDesktopIconSolid,
  CpuChipIconSolid,
  CreditCardIconSolid,
  CubeIconSolid,
  CubeTransparentIconSolid,
  CurrencyBangladeshiIconSolid,
  CurrencyDollarIconSolid,
  CurrencyEuroIconSolid,
  CurrencyPoundIconSolid,
  CurrencyRupeeIconSolid,
  CurrencyYenIconSolid,
  CursorArrowRaysIconSolid,
  CursorArrowRippleIconSolid,
  DevicePhoneMobileIconSolid,
  DeviceTabletIconSolid,
  DocumentArrowDownIconSolid,
  DocumentArrowUpIconSolid,
  DocumentChartBarIconSolid,
  DocumentCheckIconSolid,
  DocumentDuplicateIconSolid,
  DocumentIconSolid,
  DocumentMagnifyingGlassIconSolid,
  DocumentMinusIconSolid,
  DocumentPlusIconSolid,
  DocumentTextIconSolid,
  EllipsisHorizontalCircleIconSolid,
  EllipsisHorizontalIconSolid,
  EllipsisVerticalIconSolid,
  EnvelopeIconSolid,
  EnvelopeOpenIconSolid,
  ExclamationCircleIconSolid,
  ExclamationTriangleIconSolid,
  EyeDropperIconSolid,
  EyeIconSolid,
  EyeSlashIconSolid,
  FaceFrownIconSolid,
  FaceSmileIconSolid,
  FilmIconSolid,
  FingerPrintIconSolid,
  FireIconSolid,
  FlagIconSolid,
  FolderArrowDownIconSolid,
  FolderIconSolid,
  FolderMinusIconSolid,
  FolderOpenIconSolid,
  FolderPlusIconSolid,
  ForwardIconSolid,
  FunnelIconSolid,
  GifIconSolid,
  GiftIconSolid,
  GiftTopIconSolid,
  GlobeAltIconSolid,
  GlobeAmericasIconSolid,
  GlobeAsiaAustraliaIconSolid,
  GlobeEuropeAfricaIconSolid,
  HandRaisedIconSolid,
  HandThumbDownIconSolid,
  HandThumbUpIconSolid,
  HashtagIconSolid,
  HeartIconSolid,
  HomeIconSolid,
  HomeModernIconSolid,
  IdentificationIconSolid,
  InboxArrowDownIconSolid,
  InboxIconSolid,
  InboxStackIconSolid,
  InformationCircleIconSolid,
  KeyIconSolid,
  LanguageIconSolid,
  LifebuoyIconSolid,
  LightBulbIconSolid,
  LinkIconSolid,
  ListBulletIconSolid,
  LockClosedIconSolid,
  LockOpenIconSolid,
  MagnifyingGlassCircleIconSolid,
  MagnifyingGlassIconSolid,
  MagnifyingGlassMinusIconSolid,
  MagnifyingGlassPlusIconSolid,
  MapIconSolid,
  MapPinIconSolid,
  MegaphoneIconSolid,
  MicrophoneIconSolid,
  MinusCircleIconSolid,
  MinusIconSolid,
  MinusSmallIconSolid,
  MoonIconSolid,
  MusicalNoteIconSolid,
  NewspaperIconSolid,
  NoSymbolIconSolid,
  PaintBrushIconSolid,
  PaperAirplaneIconSolid,
  PaperClipIconSolid,
  PauseCircleIconSolid,
  PauseIconSolid,
  PencilIconSolid,
  PencilSquareIconSolid,
  PhoneArrowDownLeftIconSolid,
  PhoneArrowUpRightIconSolid,
  PhoneIconSolid,
  PhoneXMarkIconSolid,
  PhotoIconSolid,
  PlayCircleIconSolid,
  PlayIconSolid,
  PlayPauseIconSolid,
  PlusCircleIconSolid,
  PlusIconSolid,
  PlusSmallIconSolid,
  PowerIconSolid,
  PresentationChartBarIconSolid,
  PresentationChartLineIconSolid,
  PrinterIconSolid,
  PuzzlePieceIconSolid,
  QrCodeIconSolid,
  QuestionMarkCircleIconSolid,
  QueueListIconSolid,
  RadioIconSolid,
  ReceiptPercentIconSolid,
  ReceiptRefundIconSolid,
  RectangleGroupIconSolid,
  RectangleStackIconSolid,
  RocketLaunchIconSolid,
  RssIconSolid,
  ScaleIconSolid,
  ScissorsIconSolid,
  ServerIconSolid,
  ServerStackIconSolid,
  ShareIconSolid,
  ShieldCheckIconSolid,
  ShieldExclamationIconSolid,
  ShoppingBagIconSolid,
  ShoppingCartIconSolid,
  SignalIconSolid,
  SignalSlashIconSolid,
  SparklesIconSolid,
  SpeakerWaveIconSolid,
  SpeakerXMarkIconSolid,
  Square2StackIconSolid,
  Square3Stack3DIconSolid,
  Squares2X2IconSolid,
  SquaresPlusIconSolid,
  StarIconSolid,
  StopCircleIconSolid,
  StopIconSolid,
  SunIconSolid,
  SwatchIconSolid,
  TableCellsIconSolid,
  TagIconSolid,
  TicketIconSolid,
  TrashIconSolid,
  TrophyIconSolid,
  TruckIconSolid,
  TvIconSolid,
  UserCircleIconSolid,
  UserGroupIconSolid,
  UserIconSolid,
  UserMinusIconSolid,
  UserPlusIconSolid,
  UsersIconSolid,
  VariableIconSolid,
  VideoCameraIconSolid,
  VideoCameraSlashIconSolid,
  ViewColumnsIconSolid,
  ViewfinderCircleIconSolid,
  WalletIconSolid,
  WifiIconSolid,
  WindowIconSolid,
  WrenchIconSolid,
  WrenchScrewdriverIconSolid,
  XCircleIconSolid,
  XMarkIconSolid
}
import color from 'tailwindcss/colors'

export default function Icon({name, type, ...props}: IconProps) {
  const Comp = icons[`${name}${type === 'solid' ? 'Solid' : 'Outline'}` as keyof typeof icons]
  return type === 'outline' ? (
    <svg
      viewBox='0 0 24 24'
      {...props}
    >
      <defs>
        <linearGradient
          id='gradient'
          x1='0%'
          y1='0%'
          x2='0%'
          y2='100%'
        >
          <stop
            offset='0%'
            stopColor={color.sky[300]}
          />
          <stop
            offset='100%'
            stopColor={color.purple[300]}
          />
        </linearGradient>
      </defs>
      <Comp
        {...props}
        className={`[&>path]:stroke-[url(#gradient)] ${props.className}`}
      />
    </svg>
  ) : (
    <Comp {...props} />
  )
}
