name: Storybook

on: pull_request

jobs:
  component-check:
    name: Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: 'Install Node'
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - uses: pnpm/action-setup@v2
        name: Install pnpm
        with:
          version: 8
          run_install: false
      - name: Install dependencies
        run: pnpm install -w www
      - name: Check for missing stories
        id: check
        run: pnpm run storybook-check
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          filePath: './storybook-check.md'
