name: Storybook

on:
  push:
    branches-ignore: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  component-check:
    continue-on-error: true
    name: Storybook
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install modules
        run: npm i
      - name: Check for missing stories
        id: check
        run: echo "summary=$(npx tsx apps/www/scripts/storybook-checker.ts)" >> $GITHUB_OUTPUT
      - name: Comment PR
        uses: thollander/actions-comment-pull-request@v2
        with:
          message: |
            ${{ steps.table.outputs.summary }}
