name: Test

on: pull_request

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build
        uses: actions/setup-node@v2
        with:
          node-version: '16.x'

      - run: npm install
      - run: npm run build
